---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vul-operator
  namespace: {{ include "vul-operator.namespace" . }}
  labels:
    {{- include "vul-operator.labels" . | nindent 4 }}
data:
  {{- with .Values.vulOperator.scanJobTolerations }}
  scanJob.tolerations: {{ . | toJson | quote }}
  {{- end }}
  {{- with .Values.nodeCollector.volumes }}
  nodeCollector.volumes: {{ . | toJson | quote }}
  {{- end }}
  {{- with .Values.nodeCollector.volumeMounts }}
  nodeCollector.volumeMounts: {{ . | toJson | quote }}
  {{- end }}
  {{- with .Values.vulOperator.scanJobAnnotations }}
  scanJob.annotations: {{ . | quote }}
  {{- end }}
  {{- with .Values.vulOperator.scanJobAutomountServiceAccountToken }}
  scanJob.automountServiceAccountToken: {{ . | quote }}
  {{- end }}
  {{- with .Values.nodeCollector.excludeNodes }}
  nodeCollector.excludeNodes: {{ . | quote }}
  {{- end }}
  {{- with .Values.vulOperator.scanJobPodTemplateLabels }}
  scanJob.podTemplateLabels: {{ . | quote }}
  {{- end }}
  {{- with .Values.vulOperator.additionalReportLabels }}
  report.additionalLabels: {{ . | quote }}
  {{- end }}
  {{- with .Values.vulOperator.scanJobNodeSelector }}
  scanJob.nodeSelector: {{ . | toJson | quote }}
  {{- end }}
  {{- with .Values.vulOperator.scanJobPodTemplatePodSecurityContext }}
  scanJob.podTemplatePodSecurityContext: {{ . | toJson | quote }}
  {{- end }}
  {{- with .Values.vulOperator.scanJobPodTemplateContainerSecurityContext }}
  scanJob.podTemplateContainerSecurityContext: {{ . | toJson | quote }}
  {{- end }}
  {{- with .Values.vulOperator.scanJobPodPriorityClassName }}
  scanJob.podPriorityClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.vulOperator.scanJobCompressLogs }}
  scanJob.compressLogs: {{ . | toJson | quote }}
  {{- end }}
  {{- if or .Values.operator.vulnerabilityScannerEnabled .Values.operator.exposedSecretScannerEnabled .Values.operator.scannerReportTTL }}
  vulnerabilityReports.scanner: {{ .Values.vulOperator.vulnerabilityReportsPlugin | quote }}
  {{- end }}
  {{- if .Values.operator.configAuditScannerEnabled }}
  configAuditReports.scanner: {{ .Values.vulOperator.configAuditReportsPlugin | quote }}
  {{- end }}
  {{- if .Values.operator.clusterComplianceEnabled }}
  compliance.failEntriesLimit: {{ required ".Values.compliance.failEntriesLimit is required" .Values.compliance.failEntriesLimit | quote }}
  {{- end }}
  {{- if .Values.vulOperator.reportResourceLabels }}
  report.resourceLabels: {{ .Values.vulOperator.reportResourceLabels | quote }}
  metrics.resourceLabelsPrefix: {{ .Values.vulOperator.metricsResourceLabelsPrefix | quote }}
  {{- end }}
  {{- if .Values.vulOperator.reportRecordFailedChecksOnly }}
  report.recordFailedChecksOnly: {{ .Values.vulOperator.reportRecordFailedChecksOnly | quote }}
  {{- end }}
  {{- if .Values.vulOperator.skipResourceByLabels }}
  skipResourceByLabels: {{ .Values.vulOperator.skipResourceByLabels | quote }}
  {{- end }}
  {{- if .Values.operator.builtInVulServer }}
  vul.serverURL: {{ printf "http://%s.%s:%s" .Values.vul.serverServiceName (include "vul-operator.namespace" .) "4954"  | quote }}
  {{- end }}
  node.collector.imageRef: "{{ .Values.nodeCollector.registry }}/{{ .Values.nodeCollector.repository }}:{{ .Values.nodeCollector.tag }}"
  {{- if .Values.nodeCollector.imagePullSecret }}
  node.collector.imagePullSecret: "{{ .Values.nodeCollector.imagePullSecret }}"
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vul-operator
  namespace: {{ include "vul-operator.namespace" . }}
  labels:
    {{- include "vul-operator.labels" . | nindent 4 }}
{{- if eq .Values.vulOperator.vulnerabilityReportsPlugin "Vul" }}
{{- if .Values.vul.createConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vul-operator-vul-config
  namespace: {{ include "vul-operator.namespace" $ }}
  labels:
    {{- include "vul-operator.labels" $ | nindent 4 }}
data:
  vul.repository: "{{ required ".Values.vul.image.registry is required" .Values.vul.image.registry }}/{{ required ".Values.vul.image.repository is required" .Values.vul.image.repository }}"
  vul.tag: {{ required ".Values.vul.image.tag is required" .Values.vul.image.tag | quote }}
  {{- if .Values.vul.image.imagePullSecret }}
  vul.imagePullSecret: {{ .Values.vul.image.imagePullSecret | quote }}
  {{- end }}
  vul.additionalVulnerabilityReportFields: {{ .Values.vul.additionalVulnerabilityReportFields | quote}}
  {{- if .Values.vul.httpProxy }}
  vul.httpProxy: {{ .Values.vul.httpProxy | quote }}
  {{- end }}
  {{- if .Values.vul.httpsProxy }}
  vul.httpsProxy: {{ .Values.vul.httpsProxy | quote }}
  {{- end }}
  {{- if .Values.vul.serverInsecure }}
  vul.serverInsecure: {{ .Values.vul.serverInsecure | quote }}
  {{- end }}
  {{- if .Values.vul.sslCertDir }}
  vul.sslCertDir: {{ .Values.vul.sslCertDir | quote }}
  {{- end }}
  {{- if .Values.vul.noProxy }}
  vul.noProxy: {{ .Values.vul.noProxy | quote }}
  {{- end }}
  {{- range $key, $registry := .Values.vul.nonSslRegistries }}
  vul.nonSslRegistry.{{ $key }}: {{ $registry | quote }}
  {{- end }}
  {{- range $key, $registry := .Values.vul.insecureRegistries }}
  vul.insecureRegistry.{{ $key }}: {{ $registry | quote }}
  {{- end }}
  {{- range $key, $registry := .Values.vul.registry.mirror }}
  vul.registry.mirror.{{ $key }}: {{ $registry | quote }}
  {{- end }}
  vul.severity: {{ .Values.vul.severity | quote }}
  vul.slow: {{ .Values.vul.slow | quote }}
  vul.dbRepository: "{{ .Values.vul.dbRegistry }}/{{ .Values.vul.dbRepository }}"
  vul.javaDbRepository: "{{ .Values.vul.javaDbRegistry }}/{{ .Values.vul.javaDbRepository }}"
  vul.command: {{ .Values.vul.command | quote }}
  {{- if .Values.vul.skipDirs }}
  vul.skipDirs: {{ .Values.vul.skipDirs | quote }}
  {{- end }}
  {{- if .Values.vul.vulnType }}
  vul.vulnType: {{ .Values.vul.vulnType | quote }}
  {{- end }}
  {{- if .Values.vul.dbRepositoryInsecure }}
  vul.dbRepositoryInsecure: {{ .Values.vul.dbRepositoryInsecure | quote }}
  {{- end }}
  {{- if .Values.vul.useBuiltinRegoPolicies }}
  vul.useBuiltinRegoPolicies: {{ .Values.vul.useBuiltinRegoPolicies | quote }}
  {{- end }}
  {{- if .Values.vul.offlineScan }}
  vul.offlineScan: {{ .Values.vul.offlineScan | quote }}
  {{- end }}
  vul.supportedConfigAuditKinds: {{ .Values.vul.supportedConfigAuditKinds | quote }}
  {{- if .Values.vul.ignoreUnfixed }}
  vul.ignoreUnfixed: {{ .Values.vul.ignoreUnfixed | quote }}
  {{- end }}
  {{- if .Values.vul.timeout }}
  vul.timeout: {{ .Values.vul.timeout | quote }}
  {{- end }}
  {{- with .Values.vul.ignoreFile }}
  vul.ignoreFile: |
{{- . | trim | nindent 4 }}
  {{- end }}
{{- range $k, $v := .Values.vul }}
  {{- if hasPrefix "ignorePolicy" $k }}
  vul.{{- $k }}: |
{{- $v | trim | nindent 4 }}
  {{- end }}
{{- end }}
  {{- if .Values.operator.builtInVulServer }}
  vul.serverURL: {{ printf "http://%s.%s:%s" .Values.vul.serverServiceName (include "vul-operator.namespace" .) "4954"  | quote }}
  vul.mode: "ClientServer"
  {{- else }}
  vul.mode: {{ .Values.vul.mode | quote }}
  {{- if eq .Values.vul.mode "ClientServer" }}
  vul.serverURL: {{ required ".Values.vul.serverURL is required" .Values.vul.serverURL | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.vul.resources }}
    {{- with .requests }}
      {{- if .cpu }}
  vul.resources.requests.cpu: {{ .cpu | quote }}
      {{- end }}
      {{- if hasKey . "memory" }}
  vul.resources.requests.memory: {{ .memory | quote }}
      {{- end }}
      {{- if hasKey . "ephemeralStorage" }}
  vul.resources.requests.ephemeral-storage: {{ .ephemeralStorage | quote }}
      {{- end }}
    {{- end }}
    {{- with .limits }}
      {{- if .cpu }}
  vul.resources.limits.cpu: {{ .cpu | quote }}
      {{- end }}
      {{- if .memory }}
  vul.resources.limits.memory: {{ .memory | quote }}
      {{- end }}
      {{- if hasKey . "ephemeralStorage" }}
  vul.resources.limits.ephemeral-storage: {{  .ephemeralStorage | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.operator.builtInVulServer }}
  VUL_LISTEN: "0.0.0.0:4954"
  VUL_CACHE_DIR: "/home/scanner/.cache/vul"
  VUL_DEBUG: {{ .Values.vul.debug | quote }}
  VUL_SKIP_UPDATE: "false"
  VUL_DB_REPOSITORY: "{{ .Values.vul.dbRegistry }}/{{ .Values.vul.dbRepository }}"
  {{- end }}
{{- end }}
{{- end }}
---
{{- if not .Values.vul.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: vul-operator-vul-config
  namespace: {{ include "vul-operator.namespace" $ }}
  labels:
    {{- include "vul-operator.labels" $ | nindent 4 }}
data:
  {{- if .Values.vul.githubToken }}
  vul.githubToken: {{ .Values.vul.githubToken | b64enc | quote }}
  {{- end }}
  {{- if or (eq .Values.vul.mode "ClientServer") .Values.operator.builtInVulServer }}
  {{- if .Values.vul.serverToken }}
  vul.serverToken: {{ .Values.vul.serverToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.vul.serverCustomHeaders }}
  vul.serverCustomHeaders: {{ .Values.vul.serverCustomHeaders | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- if .Values.operator.builtInVulServer }}
  {{- if .Values.vul.githubToken }}
  GITHUB_TOKEN: {{ .Values.vul.githubToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.vul.serverToken }}
  VUL_TOKEN: {{ .Values.vul.serverToken | b64enc | quote }}
  {{- end }}
  VUL_USERNAME: {{ .Values.vul.serverUser  | b64enc | quote }}
  VUL_PASSWORD: {{ .Values.vul.serverPassword  | b64enc | quote }}
{{- end }}
{{- end }}
