{{- if and (eq .Values.serviceMonitor.enabled true) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vul-operator.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default (include "vul-operator.namespace" . ) }}
  labels:
    {{- include "vul-operator.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames:
    - {{ include "vul-operator.namespace" . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vul-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - honorLabels: {{ .Values.serviceMonitor.honorLabels | default true }}
    port: metrics
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    scheme: http
{{- end }}
