{{- if .Values.operator.builtInVulServer }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vul.serverServiceName }}
  namespace: {{ include "vul-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: vul-server
    app.kubernetes.io/instance: vul-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vul-server
    app.kubernetes.io/instance: vul-server
  ports:
    - name: vul-http
      protocol: TCP
      port: 4954
      targetPort: 4954
  sessionAffinity: ClientIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vul-server
  namespace: {{ include "vul-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: vul-server
    app.kubernetes.io/instance: vul-server
spec:
  podManagementPolicy: "Parallel"
  serviceName: {{ .Values.vul.serverServiceName }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vul-server
      app.kubernetes.io/instance: vul-server
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.vul.storageClassName }}
  template:
    metadata:
      annotations:
        checksum/config: 7fcc66ace3f98462349856795765021e7bf7a0106f28439a9f6dc74257404370
      labels:
        {{- with .Values.vul.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/name: vul-server
        app.kubernetes.io/instance: vul-server
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.vul.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "vul-operator.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- if .Values.vul.server.podSecurityContext }}
      securityContext:
{{ toYaml .Values.vul.server.podSecurityContext | indent 8 }}
      {{- end }}
      {{- if .Values.vul.image.imagePullSecret }}
      imagePullSecrets:
      - name:  {{ .Values.vul.image.imagePullSecret }}
      {{- end }}
      containers:
        - name: main
          image: "{{ .Values.vul.image.registry }}/{{ .Values.vul.image.repository }}:{{ .Values.vul.image.tag }}"
          imagePullPolicy: "IfNotPresent"
          {{- if .Values.vul.server.securityContext }}
          securityContext:
{{ toYaml .Values.vul.server.securityContext | indent 12 }}
          {{- end }}
          args:
            - server
          {{- if or (or .Values.vul.httpProxy .Values.vul.httpsProxy) .Values.vul.noProxy }}
          env:
            {{- if .Values.vul.httpProxy }}
            - name: HTTP_PROXY
              value: {{ .Values.vul.httpProxy }}
            {{- end }}
            {{- if .Values.vul.httpsProxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.vul.httpsProxy }}
            {{- end }}
            {{- if .Values.vul.noProxy }}
            - name: NO_PROXY
              value: {{ .Values.vul.noProxy }}
            {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: vul-operator-vul-config
            - secretRef:
                name: vul-operator-vul-config
          ports:
            - name: vul-http
              containerPort: 4954
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: vul-http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: vul-http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /tmp
              name: tmp-data
              readOnly: false
            - mountPath: /home/scanner/.cache
              name: data
              readOnly: false
          {{- with .Values.vul.server }}
          resources:
            {{- .resources | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp-data
          emptyDir: {}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
{{- end}}
